version: "3"
services:
  app:
    container_name: marlon-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${PORT}"


  # Add other services (e.g., a database service) if necessary
